In [3]:
import numpy as np


def main() :
    Score = np.random.randint(100, size=(10, 4))
    PrintScore(Score)
    MathScore(Score)
    TotalScore(Score)
    BooleanScore(Score)
    EngScore(Score)
    

def PrintScore(Score) :
    print(Score) 
    
    
def MathScore(Score) :
    for i in range(10) :
        MathScore = Score[i, 2:3]
        print(i, '번째 학생의 수학 점수 :', MathScore)
        
def TotalScore(Score) :
    for i in range(10) :
        TotalScore = 0
        for j in range(4) :
            TotalScore += Score[i][j]
        print(i, '번째 학생의 과목 총합 점수 :', TotalScore)
        
        
def BooleanScore(Score) :
    for i in range(10) :
        if i % 2 != 0 :
            data = Score[i:i+1, :]
            print(i, '번째 학생의 과학, 수학, 국어, 영어 점수 :', np.flip(data, axis=1))
            
    
        
        
def MaxScore(Score) :
    subject = ['국어', '영어', '수학', '과학']
    for i in range(4) :
        maxScore = max(Score[:, i:i+1])
        print(subject[i], '과목의 최고 점수 :', maxScore)
        
        
        
        
        
def EngScore(Score) :
    for i in range(10) :
        data = Score[i][1] < 90
        if data == True :
            print(i, '번째 학생의 영어 점수는 90점 미만이며,', Score[i][1], '점 입니다.')

        
    
    
    
main()
    

[[98 93 43 18]
 [57 66 84 56]
 [27 87 89 59]
 [94  8 45 51]
 [95 24 73 50]
 [47 96  5 96]
 [41 93 78 73]
 [88  6  6 18]
 [33  2 59 98]
 [ 0 89 43 64]]
0 번째 학생의 수학 점수 : [43]
1 번째 학생의 수학 점수 : [84]
2 번째 학생의 수학 점수 : [89]
3 번째 학생의 수학 점수 : [45]
4 번째 학생의 수학 점수 : [73]
5 번째 학생의 수학 점수 : [5]
6 번째 학생의 수학 점수 : [78]
7 번째 학생의 수학 점수 : [6]
8 번째 학생의 수학 점수 : [59]
9 번째 학생의 수학 점수 : [43]
0 번째 학생의 과목 총합 점수 : 252
1 번째 학생의 과목 총합 점수 : 263
2 번째 학생의 과목 총합 점수 : 262
3 번째 학생의 과목 총합 점수 : 198
4 번째 학생의 과목 총합 점수 : 242
5 번째 학생의 과목 총합 점수 : 244
6 번째 학생의 과목 총합 점수 : 285
7 번째 학생의 과목 총합 점수 : 118
8 번째 학생의 과목 총합 점수 : 192
9 번째 학생의 과목 총합 점수 : 196
1 번째 학생의 과학, 수학, 국어, 영어 점수 : [[56 84 66 57]]
3 번째 학생의 과학, 수학, 국어, 영어 점수 : [[51 45  8 94]]
5 번째 학생의 과학, 수학, 국어, 영어 점수 : [[96  5 96 47]]
7 번째 학생의 과학, 수학, 국어, 영어 점수 : [[18  6  6 88]]
9 번째 학생의 과학, 수학, 국어, 영어 점수 : [[64 43 89  0]]
1 번째 학생의 영어 점수는 90점 미만이며, 66 점 입니다.
2 번째 학생의 영어 점수는 90점 미만이며, 87 점 입니다.
3 번째 학생의 영어 점수는 90점 미만이며, 8 점 입니다.
4 번째 학생의 영어 점수는 90점 미만이며, 24 점 입니다.
7 번째 학생의 영어 점수는 90점 미만이